update mapids set locationname='Talking Island' where mapid=0;
update mapids set locationname='Talking Island Dungeon Floor 1' where mapid=1;
update mapids set locationname='Talking Island Dungeon Floor 2' where mapid=2;
update mapids set locationname='Gunters House' where mapid=3;
update mapids set locationname='Mainland Aden' where mapid=4;
update mapids set locationname='Ship to Gludin' where mapid=5;
update mapids set locationname='Ship to Talking Island' where mapid=6;
update mapids set locationname='Gludio Dungeon Floor 1' where mapid=7;
update mapids set locationname='Gludio Dungeon Floor 2' where mapid=8;
update mapids set locationname='Gludio Dungeon Floor 3' where mapid=9;
update mapids set locationname='Gludio Dungeon Floor 4' where mapid=10;
update mapids set locationname='Gludio Dungeon Floor 5' where mapid=11;
update mapids set locationname='Gludio Dungeon Floor 6' where mapid=12;
update mapids set locationname='Gludio Dungeon Floor 7' where mapid=13;
update mapids set locationname='Underground Passageway' where mapid=14;
update mapids set locationname='Kent Inner Castle' where mapid=15;
update mapids set locationname='Hardin`s Laboratory' where mapid=16;
update mapids set locationname='Nerupa\'s Cave' where mapid=17;
update mapids set locationname='Dupelgenon Dungeon' where mapid=18;
update mapids set locationname='Elven Forest Dungeon Floor 1' where mapid=19;
update mapids set locationname='Elven Forest Dungeon Floor 2' where mapid=20;
update mapids set locationname='Elven Forest Dungeon Floor 3' where mapid=21;
update mapids set locationname='Gerard`s Test Dungeon' where mapid=22;
update mapids set locationname='Windawood Castle Dungeon 1F' where mapid=23;
update mapids set locationname='Windawood Castle Dungeon 2F' where mapid=24;
update mapids set locationname='Training Dungeon Floor 1' where mapid=25;
update mapids set locationname='Training Dungeon Floor 2' where mapid=26;
update mapids set locationname='Training Dungeon Floor 3' where mapid=27;
update mapids set locationname='Training Dungeon Floor 4' where mapid=28;
update mapids set locationname='Windawood Inner Castle' where mapid=29;
update mapids set locationname='Dragon Valley Dungeon Floor 1' where mapid=30;
update mapids set locationname='Dragon Valley Dungeon Floor 2' where mapid=31;
update mapids set locationname='Dragon Valley Dungeon Floor 3' where mapid=32;
update mapids set locationname='Dragon Valley Dungeon Floor 4' where mapid=33;
update mapids set locationname='Hall of Honor' where mapid=34;
update mapids set locationname='Dragon Valley Dungeon Floor 5' where mapid=35;
update mapids set locationname='Dragon Valley Dungeon Floor 6' where mapid=36;
update mapids set locationname='Lair of Antharas' where mapid=37;
update mapids set locationname='Hall of Honor' where mapid=38;
update mapids set locationname='Hall of Honor' where mapid=39;
update mapids set locationname='Hall of Honor' where mapid=40;
update mapids set locationname='Hall of Honor' where mapid=41;
update mapids set locationname='Ant Caves 9F' where mapid=51;
update mapids set locationname='Ant Caves 8F' where mapid=50;
update mapids set locationname='Ant Caves 7F' where mapid=49;
update mapids set locationname='Ant Caves 6F' where mapid=48;
update mapids set locationname='Ant Caves 5F' where mapid=47;
update mapids set locationname='Ant Caves 4F' where mapid=46;
update mapids set locationname='Ant Caves 3F' where mapid=45;
update mapids set locationname='Ant Caves 2F' where mapid=44;
update mapids set locationname='Ant Caves 1F' where mapid=43;
update mapids set locationname='Giran Inner Castle' where mapid=52;
update mapids set locationname='Giran Prison Floor 1' where mapid=53;
update mapids set locationname='Giran Prison Floor 2' where mapid=54;
update mapids set locationname='Giran Prison Floor 3' where mapid=55;
update mapids set locationname='Giran Prison Floor 4' where mapid=56;
update mapids set locationname='Singing Island' where mapid=57;
update mapids set locationname='Hidden Valley' where mapid=58;
update mapids set locationname='Eva Kingdom Dungeon Floor 1' where mapid=59;
update mapids set locationname='Eva Kingdom Dungeon Floor 2' where mapid=60;
update mapids set locationname='Eva Kingdom Dungeon Floor 3' where mapid=61;
update mapids set locationname='Sanctuary of Eva' where mapid=62;
update mapids set locationname='Kingdom of Eva' where mapid=63;
update mapids set locationname='Heine Inner Castle' where mapid=64;
update mapids set locationname='Lair of Fafurion' where mapid=65;
update mapids set locationname='Iron Gate Guild Inner Castle' where mapid=66;
update mapids set locationname='Lair of Valakas' where mapid=67;
update mapids set locationname='Singing Island' where mapid=68;
update mapids set locationname='Hidden Valley' where mapid=69;
update mapids set locationname='Forgotten Island' where mapid=70;
update mapids set locationname='Ice Crystal Cave' where mapid=72;
update mapids set locationname='Ice Queens Castle 2F' where mapid=73;
update mapids set locationname='Ice Queens Castle 3F' where mapid=74;
update mapids set locationname='Oren Ivory Tower Floor 1' where mapid=75;
update mapids set locationname='Oren Ivory Tower Floor 2' where mapid=76;
update mapids set locationname='Oren Ivory Tower Floor 3' where mapid=77;
update mapids set locationname='Oren Ivory Tower Floor 4' where mapid=78;
update mapids set locationname='Oren Ivory Tower Floor 5' where mapid=79;
update mapids set locationname='Oren Ivory Tower Floor 6' where mapid=80;
update mapids set locationname='Oren Ivory Tower Floor 7' where mapid=81;
update mapids set locationname='Oren Ivory Tower Floor 8' where mapid=82;
update mapids set locationname='Ship to Forgotten Island' where mapid=83;
update mapids set locationname='Ship to Heine' where mapid=84;
update mapids set locationname='Singing Island Dungeon' where mapid=85;
update mapids set locationname='Hidden Valley Dungeon' where mapid=86;
update mapids set locationname='Pago\'s Room' where mapid=87;
update mapids set locationname='Giran Colosseum' where mapid=88;
update mapids set locationname='Giran Colosseum' where mapid=89;
update mapids set locationname='Giran Colosseum' where mapid=90;
update mapids set locationname='Talking island Colosseum' where mapid=91;
update mapids set locationname='Gludio Colosseum' where mapid=92;
update mapids set locationname='Kent Colosseum' where mapid=93;
update mapids set locationname='Windawood Colosseum' where mapid=94;
update mapids set locationname='Silver knight Colosseum' where mapid=95;
update mapids set locationname='Lair of Valakas Colosseum' where mapid=96;
update mapids set locationname='Heine Colosseum' where mapid=97;
update mapids set locationname='Werldern Colosseum' where mapid=98;
update mapids set locationname='Manager\'s Room' where mapid=99;
update mapids set locationname='Tower of Insolence 1F' where mapid=101;
update mapids set locationname='Tower of Insolence 2F' where mapid=102;
update mapids set locationname='Tower of Insolence 3F' where mapid=103;
update mapids set locationname='Tower of Insolence 4F' where mapid=104;
update mapids set locationname='Tower of Insolence 5F' where mapid=105;
update mapids set locationname='Tower of Insolence 6F' where mapid=106;
update mapids set locationname='Tower of Insolence 7F' where mapid=107;
update mapids set locationname='Tower of Insolence 8F' where mapid=108;
update mapids set locationname='Tower of Insolence 9F' where mapid=109;
update mapids set locationname='Tower of Insolence 10F' where mapid=110;
update mapids set locationname='Tower of Insolence 11F' where mapid=111;
update mapids set locationname='Tower of Insolence 12F' where mapid=112;
update mapids set locationname='Tower of Insolence 13F' where mapid=113;
update mapids set locationname='Tower of Insolence 14F' where mapid=114;
update mapids set locationname='Tower of Insolence 15F' where mapid=115;
update mapids set locationname='Tower of Insolence 16F' where mapid=116;
update mapids set locationname='Tower of Insolence 17F' where mapid=117;
update mapids set locationname='Tower of Insolence 18F' where mapid=118;
update mapids set locationname='Tower of Insolence 19F' where mapid=119;
update mapids set locationname='Tower of Insolence 20F' where mapid=120;
update mapids set locationname='Tower of Insolence 21F' where mapid=121;
update mapids set locationname='Tower of Insolence 22F' where mapid=122;
update mapids set locationname='Tower of Insolence 23F' where mapid=123;
update mapids set locationname='Tower of Insolence 24F' where mapid=124;
update mapids set locationname='Tower of Insolence 25F' where mapid=125;
update mapids set locationname='Tower of Insolence 26F' where mapid=126;
update mapids set locationname='Tower of Insolence 27F' where mapid=127;
update mapids set locationname='Tower of Insolence 28F' where mapid=128;
update mapids set locationname='Tower of Insolence 29F' where mapid=129;
update mapids set locationname='Tower of Insolence 30F' where mapid=130;
update mapids set locationname='Tower of Insolence 31F' where mapid=131;
update mapids set locationname='Tower of Insolence 32F' where mapid=132;
update mapids set locationname='Tower of Insolence 33F' where mapid=133;
update mapids set locationname='Tower of Insolence 34F' where mapid=134;
update mapids set locationname='Tower of Insolence 35F' where mapid=135;
update mapids set locationname='Tower of Insolence 36F' where mapid=136;
update mapids set locationname='Tower of Insolence 37F' where mapid=137;
update mapids set locationname='Tower of Insolence 38F' where mapid=138;
update mapids set locationname='Tower of Insolence 39F' where mapid=139;
update mapids set locationname='Tower of Insolence 40F' where mapid=140;
update mapids set locationname='Tower of Insolence 41F' where mapid=141;
update mapids set locationname='Tower of Insolence 42F' where mapid=142;
update mapids set locationname='Tower of Insolence 43F' where mapid=143;
update mapids set locationname='Tower of Insolence 44F' where mapid=144;
update mapids set locationname='Tower of Insolence 45F' where mapid=145;
update mapids set locationname='Tower of Insolence 46F' where mapid=146;
update mapids set locationname='Tower of Insolence 47F' where mapid=147;
update mapids set locationname='Tower of Insolence 48F' where mapid=148;
update mapids set locationname='Tower of Insolence 49F' where mapid=149;
update mapids set locationname='Tower of Insolence 50F' where mapid=150;
update mapids set locationname='Tower of Insolence 51F' where mapid=151;
update mapids set locationname='Tower of Insolence 52F' where mapid=152;
update mapids set locationname='Tower of Insolence 53F' where mapid=153;
update mapids set locationname='Tower of Insolence 54F' where mapid=154;
update mapids set locationname='Tower of Insolence 55F' where mapid=155;
update mapids set locationname='Tower of Insolence 56F' where mapid=156;
update mapids set locationname='Tower of Insolence 57F' where mapid=157;
update mapids set locationname='Tower of Insolence 58F' where mapid=158;
update mapids set locationname='Tower of Insolence 59F' where mapid=159;
update mapids set locationname='Tower of Insolence 60F' where mapid=160;
update mapids set locationname='Tower of Insolence 61F' where mapid=161;
update mapids set locationname='Tower of Insolence 62F' where mapid=162;
update mapids set locationname='Tower of Insolence 63F' where mapid=163;
update mapids set locationname='Tower of Insolence 64F' where mapid=164;
update mapids set locationname='Tower of Insolence 65F' where mapid=165;
update mapids set locationname='Tower of Insolence 66F' where mapid=166;
update mapids set locationname='Tower of Insolence 67F' where mapid=167;
update mapids set locationname='Tower of Insolence 68F' where mapid=168;
update mapids set locationname='Tower of Insolence 69F' where mapid=169;
update mapids set locationname='Tower of Insolence 70F' where mapid=170;
update mapids set locationname='Tower of Insolence 71F' where mapid=171;
update mapids set locationname='Tower of Insolence 72F' where mapid=172;
update mapids set locationname='Tower of Insolence 73F' where mapid=173;
update mapids set locationname='Tower of Insolence 74F' where mapid=174;
update mapids set locationname='Tower of Insolence 75F' where mapid=175;
update mapids set locationname='Tower of Insolence 76F' where mapid=176;
update mapids set locationname='Tower of Insolence 77F' where mapid=177;
update mapids set locationname='Tower of Insolence 78F' where mapid=178;
update mapids set locationname='Tower of Insolence 79F' where mapid=179;
update mapids set locationname='Tower of Insolence 80F' where mapid=180;
update mapids set locationname='Tower of Insolence 81F' where mapid=181;
update mapids set locationname='Tower of Insolence 82F' where mapid=182;
update mapids set locationname='Tower of Insolence 83F' where mapid=183;
update mapids set locationname='Tower of Insolence 84F' where mapid=184;
update mapids set locationname='Tower of Insolence 85F' where mapid=185;
update mapids set locationname='Tower of Insolence 86F' where mapid=186;
update mapids set locationname='Tower of Insolence 87F' where mapid=187;
update mapids set locationname='Tower of Insolence 88F' where mapid=188;
update mapids set locationname='Tower of Insolence 89F' where mapid=189;
update mapids set locationname='Tower of Insolence 90F' where mapid=190;
update mapids set locationname='Tower of Insolence 91F' where mapid=191;
update mapids set locationname='Tower of Insolence 92F' where mapid=192;
update mapids set locationname='Tower of Insolence 93F' where mapid=193;
update mapids set locationname='Tower of Insolence 94F' where mapid=194;
update mapids set locationname='Tower of Insolence 95F' where mapid=195;
update mapids set locationname='Tower of Insolence 96F' where mapid=196;
update mapids set locationname='Tower of Insolence 97F' where mapid=197;
update mapids set locationname='Tower of Insolence 98F' where mapid=198;
update mapids set locationname='Tower of Insolence 99F' where mapid=199;
update mapids set locationname='Tower of Insolence 100F' where mapid=200;
update mapids set locationname='Mage quest dungeon' where mapid=201;
update mapids set locationname='Mage Quest Dungeon' where mapid=202;
update mapids set locationname='Mage Quest Dungeon' where mapid=203;
update mapids set locationname='Mage Quest Dungeon' where mapid=204;
update mapids set locationname='Darkelf dungeon' where mapid=209;
update mapids set locationname='Darkelf dungeon' where mapid=210;
update mapids set locationname='Darkelf dungeon' where mapid=211;
update mapids set locationname='Darkelf dungeon' where mapid=213;
update mapids set locationname='Mutant ant dungeon' where mapid=217;
update mapids set locationname='Gerard test dungeon' where mapid=221;
update mapids set locationname='Jim dungeon' where mapid=237;
update mapids set locationname='Kent Castle Dungeon 1F' where mapid=240;
update mapids set locationname='Kent Castle Dungeon 2F' where mapid=241;
update mapids set locationname='Kent Castle Dungeon 3F' where mapid=242;
update mapids set locationname='Kent Castle Dungeon 4F' where mapid=243;
update mapids set locationname='Polluted Land of Blessing' where mapid=244;
update mapids set locationname='1F Taros underground Dungeon' where mapid=248;
update mapids set locationname='2F Coveters Trap' where mapid=249;
update mapids set locationname='3F Hall of Greed' where mapid=250;
update mapids set locationname='4F Counts Room' where mapid=251;
update mapids set locationname='Heine Basement Prison' where mapid=252;
update mapids set locationname='Kingdom of Eva' where mapid=253;
update mapids set locationname='Barbados\'s Hideout' where mapid=254;
update mapids set locationname='Dwarf Mine' where mapid=255;
update mapids set locationname='Wilderness' where mapid=256;
update mapids set locationname='Basement Floor 1 Path of the Dead' where mapid=257;
update mapids set locationname='Basement Floor 2 Grave of the Dead' where mapid=258;
update mapids set locationname='Basement Floor 3 Path of the Dead' where mapid=259;
update mapids set locationname='Aden Inner Castle' where mapid=300;
update mapids set locationname='Tower of Insolence Underground Path' where mapid=301;
update mapids set locationname='Sepia Dungeon' where mapid=302;
update mapids set locationname='Island of Dreams' where mapid=303;
update mapids set locationname='Cave of Silence' where mapid=304;
update mapids set locationname='Lair of Bludika' where mapid=305;
update mapids set locationname='Dark Elf Quest Dungeon' where mapid=306;
update mapids set locationname='Lastabad Dungeon 3F' where mapid=309;
update mapids set locationname='Lastabad Dungeon 2F' where mapid=308;
update mapids set locationname='Lastabad Dungeon 1F' where mapid=307;
update mapids set locationname='Oum Dungeon' where mapid=310;
update mapids set locationname='Diad Fortress' where mapid=320;
update mapids set locationname='Mineral Cave' where mapid=330;
update mapids set locationname='Gludin Market' where mapid=340;
update mapids set locationname='Giran Market' where mapid=350;
update mapids set locationname='Oren Market' where mapid=360;
update mapids set locationname='Silver Knight Town Market' where mapid=370;
update mapids set locationname='All Associations Region' where mapid=400;
update mapids set locationname='Large Cavern route' where mapid=401;
update mapids set locationname='Sanctuary of Evil' where mapid=410;
update mapids set locationname='Abyss Lake' where mapid=420;
update mapids set locationname='Elemental Grave' where mapid=430;
update mapids set locationname='Pirate Island First Part' where mapid=440;
update mapids set locationname='Pirate Island Dungeon 1F' where mapid=441;
update mapids set locationname='Pirate Island Dungeon 2F' where mapid=442;
update mapids set locationname='Pirate Island Dungeon 3F' where mapid=443;
update mapids set locationname='Pirate Island Dungeon 4F' where mapid=444;
update mapids set locationname='Hidden dock to Pirate island' where mapid=445;
update mapids set locationname='Ship to Hidden to Dock' where mapid=446;
update mapids set locationname='Ship to Pirate Island' where mapid=447;
update mapids set locationname='Lastavard Main Gate' where mapid=450;
update mapids set locationname='1st Floor Meeting Area' where mapid=451;
update mapids set locationname='1st Floor Shock Squad Training Area' where mapid=452;
update mapids set locationname='1st Floor Evil Power King\'s Power Room' where mapid=453;
update mapids set locationname='1st Floor Dark Warrens' where mapid=454;
update mapids set locationname='1st Floor Dark Warrens' where mapid=455;
update mapids set locationname='1st Floor Evil Power Summoning Room' where mapid=456;
update mapids set locationname='1st Floor Off-Limits Area of Darkness' where mapid=457;
update mapids set locationname='2nd Floor Dark Magic Training Area' where mapid=460;
update mapids set locationname='2nd Floor Dark Magic Laboratory' where mapid=461;
update mapids set locationname='2nd Floor Evil Spirit King\'s Power Room' where mapid=462;
update mapids set locationname='2nd Floor Evil Spirit King\'s Library' where mapid=463;
update mapids set locationname='2nd Floor Spirit Summoning Room' where mapid=464;
update mapids set locationname='2nd Floor Spirit Abode' where mapid=465;
update mapids set locationname='2nd Floor Dark Spirit Laboratory' where mapid=466;
update mapids set locationname='2nd Floor Closed Place of Darkness' where mapid=467;
update mapids set locationname='2nd Floor Closed Place of Darkness' where mapid=468;
update mapids set locationname='3rd Floor Evil Spirit Altar' where mapid=470;
update mapids set locationname='3rd Floor Devil Road Altar' where mapid=471;
update mapids set locationname='3rd Floor Mercenary Training Area' where mapid=472;
update mapids set locationname='3rd Floor Arcane Army Training Area' where mapid=473;
update mapids set locationname='3rd Floor Oum Experiment Room' where mapid=474;
update mapids set locationname='3rd Floor Arcane King\'s Power Room' where mapid=475;
update mapids set locationname='3rd Floor Central Control Room' where mapid=476;
update mapids set locationname='3rd Floor Devil Road Mercenary Room' where mapid=477;
update mapids set locationname='3rd Floor Control Area' where mapid=478;
update mapids set locationname='Pirate\'s Isle' where mapid=480;
update mapids set locationname='Kamyla\'s Room' where mapid=481;
update mapids set locationname='Franco\'s Labyrinth' where mapid=482;
update mapids set locationname='Closed Jail of Diego' where mapid=483;
update mapids set locationname='Underground Jail of Jose' where mapid=484;
update mapids set locationname='Underground Training Area' where mapid=490;
update mapids set locationname='Underground Passageway' where mapid=491;
update mapids set locationname='Assassin King\'s Power Room' where mapid=492;
update mapids set locationname='Underground Control Room' where mapid=493;
update mapids set locationname='Underground Punishment Area' where mapid=494;
update mapids set locationname='Underground Duel Area' where mapid=495;
update mapids set locationname='Underground Jail' where mapid=496;
update mapids set locationname='KR_Event' where mapid=500;
update mapids set locationname='KR_Event' where mapid=501;
update mapids set locationname='KR_Event' where mapid=502;
update mapids set locationname='KR_Event' where mapid=503;
update mapids set locationname='KR_Event' where mapid=504;
update mapids set locationname='KR_Event' where mapid=505;
update mapids set locationname='KR_Event' where mapid=506;
update mapids set locationname='KR_Event' where mapid=507;
update mapids set locationname='KR_Event' where mapid=508;
update mapids set locationname='Chaos Battle Collosseum' where mapid=509;
update mapids set locationname='KR_Event' where mapid=511;
update mapids set locationname='KR_Event' where mapid=512;
update mapids set locationname='KR_Event' where mapid=513;
update mapids set locationname='KR_Event' where mapid=514;
update mapids set locationname='KR_Event' where mapid=515;
update mapids set locationname='KR_Event' where mapid=516;
update mapids set locationname='Shadow Temple Outline' where mapid=521;
update mapids set locationname='Shadow Temple Floor 1' where mapid=522;
update mapids set locationname='Shadow Temple Floor 2' where mapid=523;
update mapids set locationname='Shadow Temple Floor 3' where mapid=524;
update mapids set locationname='4th Floor1' where mapid=530;
update mapids set locationname='4th Floor2' where mapid=531;
update mapids set locationname='4th Floor3' where mapid=532;
update mapids set locationname='4th Floor4' where mapid=533;
update mapids set locationname='4th Floor5' where mapid=534;
update mapids set locationname='Dark Elf Holy Lands' where mapid=535;
update mapids set locationname='3rd Floor Closed Place of Darkness' where mapid=536;
update mapids set locationname='Ant Cave' where mapid=541;
update mapids set locationname='Ant Cave' where mapid=542;
update mapids set locationname='Lair of Giant Ant Queen' where mapid=543;
update mapids set locationname='Watery Grave of Spirit' where mapid=550;
update mapids set locationname='Grave of Ships 1F-1' where mapid=551;
update mapids set locationname='Grave of Ships 1F-2' where mapid=552;
update mapids set locationname='Grave of Ships 1F-3' where mapid=553;
update mapids set locationname='Grave of Ships 2F-1' where mapid=554;
update mapids set locationname='Grave of Ships 2F-2' where mapid=555;
update mapids set locationname='Grave of Ships 2F-3' where mapid=556;
update mapids set locationname='Grave of Ships 3F' where mapid=557;
update mapids set locationname='Deep Sea Grave of Spirit' where mapid=558;
update mapids set locationname='Cave of Desire Outland' where mapid=600;
update mapids set locationname='Cave of Desire lobby' where mapid=601;
update mapids set locationname='Varloks Audience Room' where mapid=602;
update mapids set locationname='Varloks Hideout' where mapid=603;
update mapids set locationname='Room of Waves' where mapid=604;
update mapids set locationname='Room of Flames' where mapid=605;
update mapids set locationname='Room of Hurricanes' where mapid=606;
update mapids set locationname='Room of Earthquakes' where mapid=607;
update mapids set locationname='Yahees Laboratory' where mapid=608;
update mapids set locationname='Sakura Forest JP Event' where mapid=610;
update mapids set locationname='Cantonment JP Event' where mapid=611;
update mapids set locationname='Fruit Forest JP Event' where mapid=612;
update mapids set locationname='Sky Castle' where mapid=630;
update mapids set locationname='Hell' where mapid=666;
update mapids set locationname='Remembrance Island' where mapid=701;
update mapids set locationname='Land of the Abandoned' where mapid=777;
update mapids set locationname='fallen cave' where mapid=778;
update mapids set locationname='fallen cave underwater' where mapid=779;
update mapids set locationname='Thebes Desert' where mapid=780;
update mapids set locationname='Thebes Pyramid Inside' where mapid=781;
update mapids set locationname='Thebes Osiris Altar' where mapid=782;
update mapids set locationname='Tikal Temple' where mapid=783;
update mapids set locationname='Kukulcan altar' where mapid=784;
update mapids set locationname='Silveria' where mapid=1000;
update mapids set locationname='Behimous' where mapid=1001;
update mapids set locationname='Forgotten Dragon Valley' where mapid=1002;
update mapids set locationname='Lair of Antharas' where mapid=1005;
update mapids set locationname='Lair of Antharas' where mapid=1006;
update mapids set locationname='Lair of Antharas' where mapid=1007;
update mapids set locationname='Lair of Antharas' where mapid=1008;
update mapids set locationname='Lair of Antharas' where mapid=1009;
update mapids set locationname='Lair of Antharas' where mapid=1010;
update mapids set locationname='Lair of Fafurion' where mapid=1011;
update mapids set locationname='Lair of Fafurion' where mapid=1012;
update mapids set locationname='Lair of Fafurion' where mapid=1013;
update mapids set locationname='Lair of Fafurion' where mapid=1014;
update mapids set locationname='Lair of Fafurion' where mapid=1015;
update mapids set locationname='Lair of Fafurion' where mapid=1016;
update mapids set locationname='Lair of Lindvior' where mapid=1017;
update mapids set locationname='Lair of Lindvior' where mapid=1018;
update mapids set locationname='Lair of Lindvior' where mapid=1019;
update mapids set locationname='Lair of Lindvior' where mapid=1020;
update mapids set locationname='Lair of Lindvior' where mapid=1021;
update mapids set locationname='Lair of Lindvior' where mapid=1022;
update mapids set locationname='Lair of Lindvior' where mapid=1023;
update mapids set locationname='Ancient Space 1F' where mapid=2000;
update mapids set locationname='Ancient Space 2F' where mapid=2001;
update mapids set locationname='Ancient Space 3F' where mapid=2002;
update mapids set locationname='Ancient Space 4F' where mapid=2003;
update mapids set locationname='KR_EVENT' where mapid=4941;
update mapids set locationname='Aden Underground house' where mapid=5001;
update mapids set locationname='Aden Underground house' where mapid=5002;
update mapids set locationname='Aden Underground house' where mapid=5003;
update mapids set locationname='Aden Underground house' where mapid=5004;
update mapids set locationname='Aden Underground house' where mapid=5005;
update mapids set locationname='Aden Underground house' where mapid=5006;
update mapids set locationname='Aden Underground house' where mapid=5007;
update mapids set locationname='Aden Underground house' where mapid=5008;
update mapids set locationname='Aden Underground house' where mapid=5009;
update mapids set locationname='Aden Underground house' where mapid=5010;
update mapids set locationname='Aden Underground house' where mapid=5011;
update mapids set locationname='Aden Underground house' where mapid=5012;
update mapids set locationname='Aden Underground house' where mapid=5013;
update mapids set locationname='Aden Underground house' where mapid=5014;
update mapids set locationname='Aden Underground house' where mapid=5015;
update mapids set locationname='Aden Underground house' where mapid=5016;
update mapids set locationname='Aden Underground house' where mapid=5017;
update mapids set locationname='Aden Underground house' where mapid=5018;
update mapids set locationname='Aden Underground house' where mapid=5019;
update mapids set locationname='Aden Underground house' where mapid=5020;
update mapids set locationname='Aden Underground house' where mapid=5021;
update mapids set locationname='Aden Underground house' where mapid=5022;
update mapids set locationname='Aden Underground house' where mapid=5023;
update mapids set locationname='Aden Underground house' where mapid=5024;
update mapids set locationname='Aden Underground house' where mapid=5025;
update mapids set locationname='Aden Underground house' where mapid=5026;
update mapids set locationname='Aden Underground house' where mapid=5027;
update mapids set locationname='Aden Underground house' where mapid=5028;
update mapids set locationname='Aden Underground house' where mapid=5029;
update mapids set locationname='Aden Underground house' where mapid=5030;
update mapids set locationname='Aden Underground house' where mapid=5031;
update mapids set locationname='Aden Underground house' where mapid=5032;
update mapids set locationname='Aden Underground house' where mapid=5033;
update mapids set locationname='Aden Underground house' where mapid=5034;
update mapids set locationname='Aden Underground house' where mapid=5035;
update mapids set locationname='Aden Underground house' where mapid=5036;
update mapids set locationname='Aden Underground house' where mapid=5037;
update mapids set locationname='Aden Underground house' where mapid=5038;
update mapids set locationname='Aden Underground house' where mapid=5039;
update mapids set locationname='Aden Underground house' where mapid=5040;
update mapids set locationname='Aden Underground house' where mapid=5041;
update mapids set locationname='Aden Underground house' where mapid=5042;
update mapids set locationname='Aden Underground house' where mapid=5043;
update mapids set locationname='Aden Underground house' where mapid=5044;
update mapids set locationname='Aden Underground house' where mapid=5045;
update mapids set locationname='Aden Underground house' where mapid=5046;
update mapids set locationname='Aden Underground house' where mapid=5047;
update mapids set locationname='Aden Underground house' where mapid=5048;
update mapids set locationname='Aden Underground house' where mapid=5049;
update mapids set locationname='Aden Underground house' where mapid=5050;
update mapids set locationname='Aden Underground house' where mapid=5051;
update mapids set locationname='Aden Underground house' where mapid=5052;
update mapids set locationname='Aden Underground house' where mapid=5053;
update mapids set locationname='Aden Underground house' where mapid=5054;
update mapids set locationname='Aden Underground house' where mapid=5055;
update mapids set locationname='Aden Underground house' where mapid=5056;
update mapids set locationname='Aden Underground house' where mapid=5057;
update mapids set locationname='Aden Underground house' where mapid=5058;
update mapids set locationname='Aden Underground house' where mapid=5059;
update mapids set locationname='Aden Underground house' where mapid=5060;
update mapids set locationname='Aden Underground house' where mapid=5061;
update mapids set locationname='Aden Underground house' where mapid=5062;
update mapids set locationname='Aden Underground house' where mapid=5063;
update mapids set locationname='Aden Underground house' where mapid=5064;
update mapids set locationname='Aden Underground house' where mapid=5065;
update mapids set locationname='Aden Underground house' where mapid=5066;
update mapids set locationname='Aden Underground house' where mapid=5067;
update mapids set locationname='Giran Underground house' where mapid=5068;
update mapids set locationname='Giran Underground house' where mapid=5069;
update mapids set locationname='Giran Underground house' where mapid=5070;
update mapids set locationname='Giran Underground house' where mapid=5071;
update mapids set locationname='Giran Underground house' where mapid=5072;
update mapids set locationname='Giran Underground house' where mapid=5073;
update mapids set locationname='Giran Underground house' where mapid=5074;
update mapids set locationname='Giran Underground house' where mapid=5075;
update mapids set locationname='Giran Underground house' where mapid=5076;
update mapids set locationname='Giran Underground house' where mapid=5077;
update mapids set locationname='Giran Underground house' where mapid=5078;
update mapids set locationname='Giran Underground house' where mapid=5079;
update mapids set locationname='Giran Underground house' where mapid=5080;
update mapids set locationname='Giran Underground house' where mapid=5081;
update mapids set locationname='Giran Underground house' where mapid=5082;
update mapids set locationname='Giran Underground house' where mapid=5083;
update mapids set locationname='Giran Underground house' where mapid=5084;
update mapids set locationname='Giran Underground house' where mapid=5085;
update mapids set locationname='Giran Underground house' where mapid=5086;
update mapids set locationname='Giran Underground house' where mapid=5087;
update mapids set locationname='Giran Underground house' where mapid=5088;
update mapids set locationname='Giran Underground house' where mapid=5089;
update mapids set locationname='Giran Underground house' where mapid=5090;
update mapids set locationname='Giran Underground house' where mapid=5091;
update mapids set locationname='Giran Underground house' where mapid=5092;
update mapids set locationname='Giran Underground house' where mapid=5093;
update mapids set locationname='Giran Underground house' where mapid=5094;
update mapids set locationname='Giran Underground house' where mapid=5095;
update mapids set locationname='Giran Underground house' where mapid=5096;
update mapids set locationname='Giran Underground house' where mapid=5097;
update mapids set locationname='Giran Underground house' where mapid=5098;
update mapids set locationname='Giran Underground house' where mapid=5099;
update mapids set locationname='Giran Underground house' where mapid=5100;
update mapids set locationname='Giran Underground house' where mapid=5101;
update mapids set locationname='Giran Underground house' where mapid=5102;
update mapids set locationname='Giran Underground house' where mapid=5103;
update mapids set locationname='Giran Underground house' where mapid=5104;
update mapids set locationname='Giran Underground house' where mapid=5105;
update mapids set locationname='Giran Underground house' where mapid=5106;
update mapids set locationname='Giran Underground house' where mapid=5107;
update mapids set locationname='Giran Underground house' where mapid=5108;
update mapids set locationname='Giran Underground house' where mapid=5109;
update mapids set locationname='Giran Underground house' where mapid=5110;
update mapids set locationname='Giran Underground house' where mapid=5111;
update mapids set locationname='Giran Underground house' where mapid=5112;
update mapids set locationname='Heine Underground house' where mapid=5113;
update mapids set locationname='Heine Underground house' where mapid=5114;
update mapids set locationname='Heine Underground house' where mapid=5115;
update mapids set locationname='Heine Underground house' where mapid=5116;
update mapids set locationname='Heine Underground house' where mapid=5117;
update mapids set locationname='Heine Underground house' where mapid=5118;
update mapids set locationname='Heine Underground house' where mapid=5119;
update mapids set locationname='Heine Underground house' where mapid=5120;
update mapids set locationname='Heine Underground house' where mapid=5121;
update mapids set locationname='Heine Underground house' where mapid=5122;
update mapids set locationname='Heine Underground house' where mapid=5123;
update mapids set locationname='Fishing place' where mapid=5124;
update mapids set locationname='petmatch place' where mapid=5125;
update mapids set locationname='petmatch place' where mapid=5131;
update mapids set locationname='petmatch place' where mapid=5132;
update mapids set locationname='petmatch place' where mapid=5133;
update mapids set locationname='petmatch place' where mapid=5134;
update mapids set locationname='Haunted house' where mapid=5140;
update mapids set locationname='Haunted house' where mapid=5141;
update mapids set locationname='Haunted house' where mapid=5142;
update mapids set locationname='InnRoom' where mapid=16384;
update mapids set locationname='InnRoom' where mapid=16896;
update mapids set locationname='InnRoom' where mapid=17408;
update mapids set locationname='InnRoom' where mapid=17920;
update mapids set locationname='InnRoom' where mapid=18432;
update mapids set locationname='InnRoom' where mapid=18944;
update mapids set locationname='InnRoom' where mapid=19456;
update mapids set locationname='InnRoom' where mapid=19968;
update mapids set locationname='InnRoom' where mapid=20480;
update mapids set locationname='InnRoom' where mapid=20992;
update mapids set locationname='InnRoom' where mapid=21504;
update mapids set locationname='InnRoom' where mapid=22016;
update mapids set locationname='InnRoom' where mapid=22528;
update mapids set locationname='InnRoom' where mapid=23040;
update mapids set locationname='InnRoom' where mapid=23552;
update mapids set locationname='InnRoom' where mapid=24064;
update mapids set locationname='InnRoom' where mapid=24576;
update mapids set locationname='InnRoom' where mapid=25088;

